# Generated by Django 5.0.2 on 2025-01-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(default='No descrition'),
            preserve_default=False,
        ),
    ]
