# Generated by Django 5.0.2 on 2025-01-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_india'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='india',
            name='category',
        ),
        migrations.RemoveField(
            model_name='india',
            name='news',
        ),
    ]
