# Generated by Django 5.0.2 on 2025-01-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_india_category_remove_india_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='India',
        ),
    ]
